### ISSUE TITLE
Error with generate map

### ISSUE THREAD

**Issue by yuanshuai220** [iamaaditya/image-compression-cnn#5]
When I run the command `python generate_map.py <image_file>`
and this error happened, my tensorflow version is 1.1.0.
```
/home/shuai/.local/lib/python2.7/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Traceback (most recent call last):
  File "generate_map.py", line 32, in <module>
    cnn.load_vgg_weights()
  File "/home/shuai/image-compression-cnn/model.py", line 33, in load_vgg_weights
    with open(hyper.vgg_weights) as f:
IOError: [Errno 2] No such file or directory: './data/caffe_layers_value.pickle'
```

**Comment by iamaaditya** [comment]
Hi @yuanshuai220 

Just change 
 self.fine_tuning = True
to
 self.fine_tuning = False

On this file:
https://github.com/iamaaditya/image-compression-cnn/blob/master/params.py#L12
